# Site settings
author: Pam Torres- Rocca
title: Pamela454
header-img: img/home-bg.png
email: pfrieze@gmail.com
copyright_name: Pam Torres- Rocca
description: > # this means to ignore newlines until "baseurl:"
  Beginners Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: pfreezer
github_username:  Pamela454

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
